image: node:10

pipelines:
  branches:
    master:
      - step:
          name: Installation
          caches:
            - node
          script:
            - npm install
          artifacts:
            - node_modules/** # Save modules for next steps
      - step:
          name: Lint
          script:
            - npm run lint
      - step:
          name: Build for prod env
          script:
            - ng build:production
          artifacts:
            - dist/** # Save build for next steps
      - step:
          name: Build for dev env
          script:
            - ng build --watch --configuration development
          artifacts:
            - dev/** # Save build for next steps
      - step:
          name: Test
          script:
            - ng test