image: openjdk:8-jdk

pipelines:
  default:
    - step:
        name: Run JMeter Tests
        script:
          - apt-get update && apt-get install -y jmeter
          - wget https://jmeter-plugins.org/get/ -O jmeter-plugins-manager.jar
          - java -cp jmeter-plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
          - PluginsManagerCMD.sh install jpgc-cmd
          - jmeter -n -t cerebri-jmeter-jenkins.jmx -l cerebri-jmeter-jenkins.log
          - PluginsManagerCMD.sh install-for-jmx cerebri-jmeter-jenkins.jmx
          - jmeter -g cerebri-jmeter-jenkins.log -o html-report
        artifacts:
          - html-report/**
