image: node:18

pipelines:
  branches:
    main:
      - step:
          name: Install Dependencies
          caches:
            - node
          script: # Install Angular CLI globally
            - npm install -g @angular/cli 
            - npm install # Install project dependencies using npm
          artifacts:
            - node_modules/** # Save modules for next steps
      - step:
          name: Build for prod env
          script:
            - npm run build
          artifacts:
            - dist/** # Save build for next steps
      - step:
          name: Build for dev env
          script:
            - npm run build
          artifacts:
            - dev/** # Save build for next steps
      - step:
          name: Test
          script:
            - npm run test