image: node:10

pipelines:
  branches:
    main:
      - step:
          name: Install Dependencies
          caches:
            - node
          script: # Install Angular CLI globally
            - npm install -g @angular/cli 
      - step: # Install project dependencies using npm
          name: Installation
          caches:
            - node
          script:
            - npm install
          artifacts:
            - node_modules/** # Save modules for next steps
      - step:
          name: Build for prod env
          script:
            - npm run build
          artifacts:
            - dist/** # Save build for next steps
      - step:
          name: Build for dev env
          script:
            - npm run build
          artifacts:
            - dev/** # Save build for next steps
      - step:
          name: Test
          script:
            - npm run test