image: node:10

pipelines:
  branches:
    main:
      - step:
          name: Install Dependencies
          caches:
            - node
          script: # Install Angular CLI globally
            - npm install -g @angular/cli 
      - step: # Install project dependencies using npm
          name: Installation
          caches:
            - node
          script:
            - npm install
          artifacts:
            - node_modules/** # Save modules for next steps
      - step:
          name: Build for prod env
          script:
            - npm run build
          artifacts:
            - dist/** # Save build for next steps
      - step:
          name: Build for dev env
          script:
            - npm run build
          artifacts:
            - dev/** # Save build for next steps
      - step:
          name: Test
          script:
            - npm run test
      - step:
          name: Run JMeter Load Tests
          script:
            - apt-get update && apt-get install -y openjdk-11-jre
            - wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz -O /tmp/apache-jmeter.tgz
            - tar -xf /tmp/apache-jmeter.tgz -C /opt
            - export PATH=$PATH:/opt/apache-jmeter-5.4.1/bin
            - jmeter -n -t /jmeter/Jmeter-file.jmx -l /jmeter/report.jtl
      - step:
          name: Upload Results
          script:
            - pipe: atlassian/bitbucket-upload-file:1.1.2
              variables:
                FILENAME: 'result.jtl'
                REPONAME: 'jmeter-test'
                FILE_KEY: '/jmeter/result.jtl'