name: CI/CD with JMeter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install -g @angular/cli
          npm install
        working-directory: ${{ github.workspace }}

      - name: Cache Apache JMeter
        uses: actions/cache@v2
        id: cache-jmeter
        with:
          path: |
            jmeter
          key: jmeter-${{ runner.os }}-${{hashFiles('**/apache-jmeter-5.4.1.tgz') }}
          restore-keys: |
            jmeter-${{ runner.os }}-

      - name: Run JMeter Load Tests
        if: steps.cache.outputs.cache-hit != 'true' 
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-11-jre
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz -O apache-jmeter.tgz
          mkdir -p jmeter
          tar -xf apache-jmeter.tgz -C jmeter

      - name: upload jmeter artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-artifact
          path: jmeter/**
          
      # - name: Download JMeter Artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: jmeter-artifact
      #     path: jmeter

      - name: Run JMeter Test
        run: |
          ls jmeter
          cd jmeter
          ./bin/jmeter -n -t jmeter/Jmeter-file.jmx -l jmeter/Jmeter-file.jtl
        shell: bash
          
        #   export PATH=$PATH:/opt/apache-jmeter-5.4.1/bin
        #   jmeter -n -t /path/to/your/Jmeter-file.jmx -l /path/to/your/report.jtl
        # working-directory: ${{ github.workspace }}

  # Uncomment and add additional jobs as needed
  # additional-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ...
